FROM quay.io/ansible/awx-ee:latest
USER root
RUN  yum update xz-libs -y
RUN yum update subversion -y
RUN yum update subversion-libs -y
RUN yum update python3 -y
RUN yum update python3-libs -y
RUN yum update python-unversioned-command -y
RUN yum update libksba -y
RUN yum update git-core -y
RUN yum update vim-minimal -y
